# USO:
# sudo docker compose -f docker-compose-server.yml  up --build -d
# sudo docker compose -f docker-compose-server.yml  down

networks:
    local-network-ia:
        name: local-network-ia
        external: true
        driver: bridge

services:
    ocrserver:
        build: .
        image: ocrserver
        container_name: ocrserver
        restart: always

        networks:
            - local-network-ia

        ports:
            - '4001:4001'

        environment:
            - NODE_ENV=production            
        
        volumes:
            - ./logs:/app/logs  # Mapeia a pasta local ./logs para persistir os logs do container